name: kaleidoscope
description: A new Flutter project.  # 앱 설명

environment:
  sdk: '^3.7.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.4
  audioplayers: ^5.2.1
  intl: ^0.18.1

flutter:
  assets:
    - assets/1.png
    - assets/2.png
    - assets/buttonoff.png
    - assets/buttonon.png
    - assets/candlescope.png
    - assets/loading.png
    - assets/logo.png
    - assets/noro.png
    - assets/setuna.png
    - assets/setuna_var.png
    - assets/waku.png
    - assets/kansei.png
    - assets/back.mp3