name: kaleidoscope
description: A new Flutter project.  # 앱 설명

environment:
  sdk: '^3.7.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  audioplayers: ^5.2.1
  intl: ^0.18.1

flutter:
  assets:
    - assets/1.png
    - assets/2.png
    - assets/buttonoff.png
    - assets/buttonon.png
    - assets/candlescope.png
    - assets/scope.png
    - assets/setuna_var_aligned_1.png
    - assets/setuna_var_aligned_2.png
    - assets/setuna_var_aligned_3.png
    - assets/setuna_var_aligned_4.png
    - assets/candle.png
    - assets/kansei_grey.png
    - assets/loading.png
    - assets/loading_red.png
    - assets/logo.png
    - assets/noro.png
    - assets/setuna.png
    - assets/setuna_var.png
    - assets/waku.png
    - assets/kansei.png
    - assets/start.png
    - assets/retry.png
    - assets/back.mp3